# Generated by Django 5.0.3 on 2024-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_fullname_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
