# Generated by Django 5.0.3 on 2024-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('isread', models.BooleanField(default=False)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
                ('registereddate', models.DateField(auto_now_add=True, null=True)),
                ('notificationtype', models.CharField(blank=True, max_length=250, null=True)),
                ('jobcategoryid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
