# Generated by Django 5.0.3 on 2024-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
