# Generated by Django 5.0.3 on 2024-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='adminname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
