# Generated by Django 5.0.3 on 2024-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_notification_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='jobcategoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
