# Generated by Django 5.0.3 on 2024-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('applieddate', models.DateField(auto_now_add=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='savejob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('saveddate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
