# Generated by Django 5.0.3 on 2024-06-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savejob',
            old_name='companyname',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='savejob',
            old_name='job_id',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='savejob',
            old_name='jobtitle',
            new_name='jobid',
        ),
        migrations.RenameField(
            model_name='savejob',
            old_name='user_id',
            new_name='userid',
        ),
    ]
