# Generated by Django 5.0.3 on 2024-06-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_rename_companyname_savejob_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='companyuserid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
