# Generated by Django 5.0.3 on 2024-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
