# Generated by Django 5.0.3 on 2024-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_applyjob_companyuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
