# Generated by Django 5.0.3 on 2024-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_skill_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='jobseeker.skill'),
        ),
    ]
