# Generated by Django 5.0.3 on 2024-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_alter_jobseeker_address_line2_jobseekereducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekereducation',
            name='education_document',
            field=models.FileField(null=True, upload_to='ed_documents/'),
        ),
    ]
