# Generated by Django 5.0.3 on 2024-06-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_jobseekereducation_education_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('job_description', models.CharField(max_length=500, null=True)),
                ('company_name', models.CharField(max_length=500, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('experience_document', models.FileField(upload_to='ex_documents/')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
