# Generated by Django 5.0.3 on 2024-06-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_jobseekerexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='skills',
            new_name='skill',
        ),
    ]
