# Generated by Django 5.0.3 on 2024-06-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_rename_skills_jobseeker_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='skill',
            new_name='skills',
        ),
    ]
