# Generated by Django 5.0.3 on 2024-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0011_rename_skill_jobseeker_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
