# Generated by Django 5.0.3 on 2024-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_alter_jobseeker_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job_category',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
