# Generated by Django 5.0.3 on 2024-06-11 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('jobcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('jobnature', models.CharField(blank=True, max_length=255, null=True)),
                ('jobvacancy', models.IntegerField(blank=True, max_length=255, null=True)),
                ('jobsalary', models.CharField(blank=True, max_length=255, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=255, null=True)),
                ('jobdescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobresponsibility', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobqualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobexperiance', models.IntegerField(blank=True, max_length=255, null=True)),
                ('jobkeywords', models.CharField(blank=True, max_length=355, null=True)),
                ('companyname', models.CharField(max_length=255, unique=True)),
                ('companylocation', models.CharField(blank=True, max_length=255, null=True)),
                ('companywebsite', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
