# Generated by Django 5.0.3 on 2024-07-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('isapproved', models.BooleanField(blank=True, default=False, null=True)),
                ('category_added_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('employee_position', models.CharField(max_length=100, null=True)),
                ('employee_phone_number', models.CharField(max_length=20, null=True)),
                ('employee_email', models.CharField(max_length=50, null=True)),
                ('employee_department', models.CharField(max_length=255, null=True)),
                ('company_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companysector')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='company_logo')),
                ('is_verified', models.BooleanField(default=False)),
                ('company_website', models.CharField(max_length=100, null=True)),
                ('company_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_name', models.ManyToManyField(null=True, to='company.companydepartment')),
                ('company_sectors', models.ManyToManyField(blank=True, to='company.companysector')),
            ],
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('jobcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('jobnature', models.CharField(blank=True, max_length=255, null=True)),
                ('jobvacancy', models.IntegerField(blank=True, null=True)),
                ('jobsalary', models.CharField(blank=True, max_length=255, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=255, null=True)),
                ('joblocationstate', models.CharField(blank=True, max_length=255, null=True)),
                ('jobdescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobresponsibility', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobqualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobexperiance', models.IntegerField(blank=True, null=True)),
                ('jobkeywords', models.CharField(blank=True, max_length=355, null=True)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('companylocation', models.CharField(blank=True, max_length=255, null=True)),
                ('companywebsite', models.CharField(blank=True, max_length=255, null=True)),
                ('jobposteddate', models.DateField(auto_now_add=True, null=True)),
                ('company_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
