# Generated by Django 5.0.3 on 2024-06-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobexperiance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobvacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
