# Generated by Django 5.0.3 on 2024-07-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobpostedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_user_id', models.IntegerField(blank=True, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('jobcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('jobnature', models.CharField(blank=True, max_length=255, null=True)),
                ('jobvacancy', models.IntegerField(blank=True, null=True)),
                ('jobsalary', models.CharField(blank=True, max_length=255, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=255, null=True)),
                ('joblocationstate', models.CharField(blank=True, max_length=255, null=True)),
                ('jobdescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobresponsibility', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobqualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('jobexperiance', models.IntegerField(blank=True, null=True)),
                ('jobkeywords', models.CharField(blank=True, max_length=355, null=True)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('companylocation', models.CharField(blank=True, max_length=255, null=True)),
                ('companywebsite', models.CharField(blank=True, max_length=255, null=True)),
                ('jobposteddate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
