# Generated by Django 5.0.3 on 2024-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_jobcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='companyname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
