# Generated by Django 5.0.3 on 2024-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_jobpostedhistory_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostedhistory',
            name='jobid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
