# Generated by Django 5.0.3 on 2024-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_jobpost_joblocationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategories',
            name='isapproved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
