# Generated by Django 5.0.3 on 2024-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_jobcategories_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategories',
            name='category_added_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
