# Generated by Django 5.0.3 on 2024-06-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companysector_department_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companysector')),
            ],
        ),
    ]
