# Generated by Django 5.0.3 on 2024-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companydepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
