# Generated by Django 5.0.3 on 2024-07-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department_name',
        ),
        migrations.AddField(
            model_name='company',
            name='department_name',
            field=models.ManyToManyField(null=True, to='company.companydepartment'),
        ),
    ]
