# Generated by Django 5.0.3 on 2024-07-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_company_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydepartment',
            name='companyid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
