# Generated by Django 5.0.3 on 2024-07-02 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_companydepartment_companyid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('employee_position', models.CharField(max_length=100, null=True)),
                ('employee_phone_number', models.CharField(max_length=20, null=True)),
                ('employee_email', models.CharField(max_length=50, null=True)),
                ('employee_department', models.CharField(max_length=255, null=True)),
                ('company_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
